services:
  - type: web
    name: guardian-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn guardian.wsgi:application"
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: your-production-secret-key
      - key: JWT_SECRET_KEY
        value: your-jwt-secret
      - key: DATABASE_URL
        fromDatabase:
          name: guardian-db
          property: connectionString
