# Generated by Django 5.2 on 2025-05-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('contact', '0002_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='channel',
        ),
        migrations.AddField(
            model_name='contact',
            name='channels',
            field=models.ManyToManyField(related_name='contacts', to='communication.communicationchannel'),
        ),
    ]
