# Generated by Django 5.2 on 2025-05-26 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_channel_contact_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='plataform',
        ),
    ]
